### ISSUE TITLE
High function numbers

### ISSUE THREAD

**Issue by Neil-McK** [DCC-EX/DCCInspector-EX#2]
Need to check for the handling of higher function numbers and add.

**Comment by FrightRisk** [comment]
I left a note on Discord. Perhaps with the combination of the NMRA doc and the RCN-212 document it will be more clear. I hope this isn't another case of interpreting a spec 2 different ways.

**Comment by Neil-McK** [comment]
Looks like the RCN again modifies DCC so full NMRA compliance means
non-compliance with RCN.

**Comment by atanisoft** [comment]
RCN *DOES* add a few extended features to the DCC specifications through the usage of reserved bit patterns but otherwise is compliant from my last review. It can safely be used as a reference for NMRA compliance *IF* you exclude the extended packet formats that were added (they are noted IIRC). There is also an effort to synchronize the two as part of an updated NMRA standard. The latest revision of docs (even drafts) is available [here](https://github.com/nmradcc/documents).

**Comment by Neil-McK** [comment]
Added decoding for function blocks 29 to 68.  Checked and corrected handling of binary state commands, both short form and long form.  Added in pull request #4.

**Comment by Neil-McK** [comment]
Many of the problems I've encountered have been rooted in the
interpretation of the NMRA specification and the RCN specification.  A
specification is not a technical design, but many people expect the spec to
address every part of how to design equipment.  In fact the spec should be
limited to those aspects of a system that must be implemented in a
particular way in order to achieve desired performance, e.g. provide
interoperation with another system that is independently developed to the
same specification.  If something isn't specified, it's because it isn't an
aspect of the system that is critical to interoperation.  It should not be
assumed that, because something doesn't appear in the spec, it isn't
permitted.  If it says the decoder must accept '1' bit lengths up to 64us,
then it may also accept longer ones, unless the spec says it must reject
them.

Additions to a spec have to be made very carefully.  For example, the spec
may include definitions for functions 1-5 out of 6 possible values.  I can
later enhance the spec by defining function 6 behaviour.  Because function
6 was not previously specified, nothing is broken.  However, if I also
reallocate function 3 to do something else, I've broken the spec as any
equipment written to comply with the original spec will by necessity be
non-compliant with the new spec.

The particular aspect of the RCN that caused problems was the tightening of
the bit lengths for DCC '0' bits.  In the NMRA specs the '1' bit is tightly
specified, but a value '0' bit may be up to 1000us in half-bit length.  The
RCN spec reduces this to max 116us for a command station.

The nominal clock rate for DCC is somewhat problematic at 58/100us
half-cycle times as this requires changes to the clock rate as much as
every cycle.  DCC++EX uses 58/116us  half-cycle times as this allows a
regular 58us clock to generate the DCC signal- on some ticks the output
changes, some it doesn't.  This is easily NMRA compliant, but for RCN the
criterion is tighter.  Any command station that generates pulses longer
than 116us is NMRA compliant but not RCN compliant.  The RCN spec, in
comparison with the NMRA spec, is broken in this aspect.

There is also a discrepancy in the use of binary state commands.  The NMRA
spec, and the RCN spec too, specifies that binary states and functions are
similar in purpose but are not the same.  Therefore, system manufacturers
may use them freely.  Function 65 may perform a different operation to
binary state 65.  Conversely, the RCN spec states that function 65 and
binary state 65 must perform the same operation - another breaking change.

So that's two areas where the RCN differs from the NMRA specs in such a way
that equipment that is NMRA compliant may not be RCN compliant.

Hope this explains where I'm coming from, and my concerns with a second
standards body tweaking an existing spec for their own reasons.

Regards, Neil

**Comment by atanisoft** [comment]
As noted the RCN specs/standards are being incorporated into the NMRA standards and are currently under review. Some aspects, like the bit timing, are likely to be revised along the way. It is an ongoing effort.

**Comment by FrightRisk** [comment]
Who do we write to? Obviously there is at least one person at each organization who know each other and trade emails, how do we get in on the conversation?

**Comment by atanisoft** [comment]
> Who do we write to?

You can try sending a message to @bakerstu who has been working with the NMRA DCC group for various revision activities.

**Comment by FrightRisk** [comment]
@Neil-McK Do you know where you saw a max of 116 for pulse duration? This is my translation of RCN-210 from Dec 1, 2019
2.1 The "1" bit, one bit

- In a one-bit, the first and second halves must have a duration of **58 µs ± 3 µs**.
- The duration of a one-bit is therefore 116 µs ± 6 µs.
- Both halves of the bit must be of the same length with a tolerance of ± 3 µs.
- A decoder must accept a tolerance for a bit half of ± 6 µs.
- This means that a decoder must recognize such received bits as valid one-bits, both parts of which each have a duration between 52 µs and 64 µs.

2.2 The "0" bit, zero bit
- The nominal duration of both halves in a zero bit is 100 µs.
**- The minimum duration of half of a zero bit is 95 µs.
- The maximum duration of half of a zero bit is
   * 9900 µs if an analog locomotive should also be controlled.
   * 116 µs to maintain compatibility with other protocols and Protocol extensions.
- The total duration of a zero bit must not exceed 12000 µs.**
- In order to keep the DC components of the complete DCC track signal at zero as with the one bits, both parts of the zero bit 
  are usually the same length.
- In order to obtain a DC voltage component for alternative control purposes, only one half of a zero bit may be extended.
- A decoder must recognize such received bits as valid zero bits, the first or second part of which has a duration between 90 µs and 10,000 µs.
All time measurements are related to the zero crossings, which are the middle between positive and negative signal amplitudes.
-------------------------------

So it depends how you read the section about 116µs.  Is this what you are talking about? It makes no sense to allow 95µs to 12000µs and then say any number in between is the limit. And if you argue that those values are only when controlling a DC loco, how do you know? Or would there be decoders, like accessory decoders, that could say, "I'm not controlling a loco, so I won't look at anything longer than 116µs"? But then it could not work on a mixed DC and DCC system.

**Comment by Neil-McK** [comment]
The bit about nominally 100us, max 116us unless controlling an analogue
loco, to maintain compatibility with other protocols.

I agree, the rcns tend to reiterate the NMRA spec then put some additional
constraint on what had already been stated.

Neil

**Comment by atanisoft** [comment]
Here is one of the first NMRA DCC standards being updated with reference to RCN: https://www.nmra.org/sites/default/files/standards/sandrp/pdf/s-9.1_electrical_standards_for_digital_command_control_2021.pdf. This covers packet timing and track voltages primarily.

**Comment by FrightRisk** [comment]
Great info Mike. That added table makes things more clear.

**Comment by Neil-McK** [comment]
This doesn't appear to have significantly changed since the January revision, and
happily still doesn't mention anything about the contentious 116us limit for
0 half-bits in the RCN spec!

**Comment by Neil-McK** [comment]
I don't understand why this discussion appears against this 'closed' change relating to function and binary state commands.  Or why it has been reopened.  Fred, please clarify.

**Comment by atanisoft** [comment]
> and happily still doesn't mention anything about the contentious 116us limit for 0 half-bits in the RCN spec!

Do you have a reference for that? The NMRA spec linked above is based off the old NMRA spec and RCN/NEM data incorporated.

**Comment by Neil-McK** [comment]
See earlier message where Fred quotes from RCN-210 from Dec 1, 2019 section 2.2.  I can't see the 116us limit in the NMRA spec, the limits on half-bit length sensibly seem to remain as they were in the original NMRA specs.

Neil

**Comment by atanisoft** [comment]
> I can't see the 116us limit in the NMRA spec, the limits on half-bit length seem to remain as they were in the original NMRA specs.

Because that limit *DOESN'T* exist. The nominal is still 100usec for the half bit with a maximum total length for both halves being 12000usec. The most likely reason it is called out in the RCN spec is to provide a practical limit on the zero half bit time. This should have zero impact on DCC++EX for compliance with NMRA or RCN since DCC++EX is within the limits anyway.

**Comment by Neil-McK** [comment]
Thank you, that is my whole point.  The RCN do not specify the DCC standard, they break it.  
The NMRA specifications are the DCC standard.  The differences in the RCN specs, for whatever reason, just lead to confusion because they are not consistent with NMRA.

And if a 116us limit were to be added, then it would effect DCC++ex, as the pulse length on the tracks is never exactly 116us. So as many as 50% of all 0 half-bits are longer than 116us and therefore outside the RCN spec, but well within the NMRA specs.

**Comment by FrightRisk** [comment]
My mistake, I hit a button! Back to closed.

**Comment by atanisoft** [comment]
RCN is intended as a clarification and extension on the NMRA standards. Some aspects are being integrated into the NMRA standards now with various WIP drafts.

**Comment by FrightRisk** [comment]
And doesn't MOROP repeat the same basic specs?

**Comment by atanisoft** [comment]
MOROP is related to RCN/NEM, it is mentioned in the draft I linked.
